# Generated by Django 5.0.6 on 2024-06-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_usuario', '0002_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('is_admin', 'Es administrador'), ('is_employee', 'Es empleado'), ('is_client', 'Es cliente')]},
        ),
    ]
